name: Mover som para pasta raw

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mover:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Mover arquivo
        run: |
          mkdir -p android/app/src/main/res/raw
          mv android/app/src/main/res/phd_alert.wav android/app/src/main/res/raw/phd_alert.wav

      - name: Salvar alteração
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add android/app/src/main/res
          git commit -m "Mover som do alerta para res/raw"
          git push
